In [4]:
import numpy as np

arr = np.ones((9, 9), dtype=np.int8)

print(arr,"\n")

arr[1:-1, 1:-1] = 0
arr[2, 2:7] = 1
arr[3, 2] = 1
arr[4, 2:4] = 1
arr[4, 5] = 1
arr[5, 2:7] = 1
arr[6, 2] = 1
arr[6, 6] = 1
arr[7, 2:7] = 1

print(arr,"\n")

[[1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]] 

[[1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 1]
 [1 0 1 1 1 1 1 0 1]
 [1 0 1 0 0 0 0 0 1]
 [1 0 1 1 0 1 0 0 1]
 [1 0 1 1 1 1 1 0 1]
 [1 0 1 0 0 0 1 0 1]
 [1 0 1 1 1 1 1 0 1]
 [1 1 1 1 1 1 1 1 1]] 

