In [31]:
import numpy as np
from sklearn.impute import SimpleImputer

train_data = [[7, 6, 5],
              [4, np.nan, 5],
              [1, 20, 8]]

In [32]:
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')

imputer.fit(train_data)

print("Question 1")
print(imputer.statistics_)

Question 1
[ 4. 13.  6.]


In [33]:
train_data_filled = imputer.transform(train_data)

print("Question 2")
print(train_data_filled)

Question 2
[[ 7.  6.  5.]
 [ 4. 13.  5.]
 [ 1. 20.  8.]]


In [34]:
test_data = [[np.nan, 3, 4],
             [2, np.nan, 6],
             [1, 8, np.nan]]

imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(train_data)
test_data_filled = imputer.transform(test_data)

In [35]:
print("Question 3")
print(test_data_filled2)

Question 3
[[ 4.  3.  4.]
 [ 2. 13.  6.]
 [ 1.  8.  6.]]
