In [29]:
import numpy as np
from sklearn.preprocessing import StandardScaler

X_train = np.array([[ 1., -1.,  2.],
                     [ 2.,  0.,  0.],
                     [ 0.,  1., -1.]])

In [30]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)

mean = np.mean(X_train_scaled, axis=0)
std = np.std(X_train_scaled, axis=0)

print("Question 1\n")
print("Mean axis on 0: ",mean,"\n")
print("Standard deviation on  axis 0: ",std,"\n")
print(X_train_scaled,"\n")

Question 1

Mean axis on 0:  [0. 0. 0.] 

Standard deviation on  axis 0:  [1. 1. 1.] 

[[ 0.         -1.22474487  1.33630621]
 [ 1.22474487  0.         -0.26726124]
 [-1.22474487  1.22474487 -1.06904497]] 



In [31]:
X_test = np.array([[ 2., -1.,  1.],
                     [ 3.,  3.,  -1.],
                     [ 1.,  1., 1.]])

In [32]:
scaler = StandardScaler()

scaler.fit(X_train)
X_test = np.array([[ 2., -1.,  1.],
                   [ 3.,  3.,  -1.],
                   [ 1.,  1., 1.]])

# Transform the test data
X_test_scaled = scaler.transform(X_test)

print("Question 2\n")
print(X_test_scaled)

Question 2

[[ 1.22474487 -1.22474487  0.53452248]
 [ 2.44948974  3.67423461 -1.06904497]
 [ 0.          1.22474487  0.53452248]]
