In [2]:
from sklearn.model_selection import train_test_split
import numpy as np

# First dataset
X = np.arange(1, 21).reshape(10, -1)
y = np.zeros(10)
y[7:] = 1

# Split the data using train_test_split with shuffle=False
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=False)

print("Question 1")
print("\nX_train:\n", X_train, "\n\n\ny_train:\n", y_train, "\n\n\nX_test:\n", X_test, "\n\n\ny_test:\n", y_test)

Question 1

X_train:
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]] 


y_train:
 [0. 0. 0. 0. 0. 0. 0. 1.] 


X_test:
 [[17 18]
 [19 20]] 


y_test:
 [1. 1.]


In [3]:
# Generate the second dataset
X = np.arange(1, 201).reshape(100, -1)
y = np.zeros(100)
y[70:] = 1

# Split the data using train_test_split with stratify parameter
X_train_strat, X_test_strat, y_train_strat, y_test_strat = train_test_split(X, y, test_size=0.2, stratify=y)

# Compute the proportion of class 1 in the stratified training and test sets
prop_class_1_train_strat = np.sum(y_train_strat == 1) / len(y_train_strat)
prop_class_1_test_strat = np.sum(y_test_strat == 1) / len(y_test_strat)

In [4]:
prop_class_1_train_strat, prop_class_1_test_strat

(0.3, 0.3)