In [3]:
from sklearn.datasets import make_regression
import numpy as np

from sklearn.model_selection import train_test_split

# Your data
X = np.arange(1,21).reshape(10,-1)
y = np.arange(1,11)

# Split the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=False)

# Print the training and testing data
print("X_train:\n", X_train)
print("\ny_train:\n", y_train)
print("\nX_test:\n", X_test)
print("\ny_test:\n", y_test)

X_train:
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]]

y_train:
 [1 2 3 4 5 6 7 8]

X_test:
 [[17 18]
 [19 20]]

y_test:
 [ 9 10]
